export interface Article {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readTime: string;
  date: string;
  content: string[];
}

export const articles: Article[] = [
  {
    slug: "stop-being-the-bottleneck-construction-business",
    title: "How to Stop Being the Bottleneck in Your Construction Business",
    excerpt: "If every decision, every problem, and every question runs through you, you're not running a business. You're just the most overworked person on the payroll.",
    category: "Systems",
    readTime: "5 min read",
    date: "18 March 2026",
    content: [
      "Think about the last time you took a day off. Not a holiday, just a normal day away from the business. Did things run fine, or did your phone not stop? If it's the latter, you're the bottleneck. The business can't move without you. Every job, every decision, every problem sits in your hands. That feels normal when you're in it, but it's the thing that stops you growing.",
      "A bottleneck in your business is anything that slows down progress or stops growth. It could be a person, a process, or a gap in your systems. Most of the time, when construction business owners come to me, they already know what it is. They just haven't worked out how to fix it. The most common one I see is the owner himself. He's brilliant at the job, clients trust him, the team knows he'll sort it. So everything gets funnelled back to him. Every question, every material decision, every variation, every complaint.",
      "The reason it happens is straightforward. You built the business from nothing. You know every job better than anyone else. You've had to do it all yourself because when you started, there was no one else. But what worked when it was just you doesn't work when you've got a team and multiple jobs on the go. At some point, carrying everything becomes the thing that holds you back.",
      "The first step is to actually track where your time goes for a week. Not roughly. Properly. Write down every task you do and how long it takes. What you'll find is that a significant chunk of your week is spent on things someone else could do. Answering the same questions from the team. Ordering materials. Chasing invoices. These are not owner tasks. They're tasks that need a process or a person.",
      "Once you can see where the time is going, you can start separating what only you can do from what doesn't need you. Site planning, client relationships, pricing strategy, business decisions. Those stay with you. Materials runs, responding to basic queries, booking in jobs, chasing payments. Those need to be handed off or turned into a system so someone else can handle them without coming back to you every five minutes.",
      "The handoff is where most people get it wrong. They delegate something, the team member gets it wrong once, and the owner takes it back. That's not delegation. That's just doing it yourself with extra steps. Proper delegation means taking the time to explain what good looks like, giving someone the authority to make decisions within that task, and trusting them to do it. It takes more time upfront. It saves you everything on the back end.",
      "There's also the mindset side of it. A lot of construction business owners hold on to everything because they feel like letting go means losing control. The opposite is true. When you're doing everything, you have the illusion of control but none of the results. When you build a team and systems that can operate without you being in every detail, you have actual control. You can see what's happening, manage it properly, and make real decisions rather than just firefighting.",
      "One thing that helps is a simple brief for every job. What's the scope, what's the timeline, what are the key materials, who's responsible for what, and what does a completed job look like. When your team has that, the number of questions that come back to you drops immediately. They have what they need. They're not coming to you because they want to, they're coming because they don't have the information to do it themselves.",
      "You didn't get into business to be the person who can never step away. Start this week by writing down the five things that only you can do. Everything else is a candidate for delegation or a process. That's where you begin.",
    ],
  },
  {
    slug: "why-construction-businesses-fail-first-5-years",
    title: "Why Most Construction Businesses Fail in the First 5 Years",
    excerpt: "It's rarely the work that kills a construction business. It's the stuff that happens around the work that nobody warned you about.",
    category: "Leadership",
    readTime: "5 min read",
    date: "11 March 2026",
    content: [
      "Most construction business owners who fail weren't bad at their trade. They were good at it. That's often what gets them into trouble. They were brilliant on the tools, clients loved them, word spread, and they found themselves with more work than they could handle on their own. So they took on staff, took on bigger jobs, took on more risk. Then something went wrong. Usually more than one thing.",
      "The most common reason construction businesses fail in the first five years isn't a bad job or a difficult client. It's cash flow. Not profit, cash flow. You can have three strong jobs on the go, invoices waiting to be paid, and still not be able to cover payroll on Friday. That's the reality of this industry. Payment terms are long, materials go on account, and your costs hit before your income does. If you don't plan for that gap, you find yourself in a hole fast.",
      "The second thing that kills businesses early is pricing. Not undercharging on materials. Undercharging on everything. I speak to construction business owners regularly who think they're making 25% margin on a job. When you sit down and work through the real numbers, including overheads, their time, the cost of rework, the variation that never got priced, they're making closer to 8%. Some are losing money on jobs and not realising it until they check the bank balance three months later.",
      "Then there's growth for the sake of it. Taking on more men, more vans, more jobs because it feels like progress. Turnover goes up and suddenly there's less money. More staff means more payroll every week regardless of whether you're being paid. More vans mean more insurance, more maintenance, more diesel. Revenue goes up, complexity goes up, and if your systems haven't kept pace, margin goes down. I've spoken to business owners doing two million a year who are more stressed and earning less than they were at half that figure.",
      "The third issue is the owner trying to do everything. When a business is small, that works. You can manage it. But it doesn't scale. As the team grows, there are more decisions to make, more problems to solve, more plates spinning. The owner who's still trying to carry all of it ends up reactive, exhausted, and making poor decisions because there's no time to think. That's when mistakes get made and jobs start running over.",
      "A lot of people also fail to build relationships properly. Chasing new clients constantly while existing clients go quiet. One of the most reliable sources of work in construction is repeat business and referrals. If your after-sales is weak, if you're not staying in touch, if clients feel like a number, they'll go to someone else next time. The business that looks after its clients well rarely has to worry too much about lead generation.",
      "What separates the businesses that make it past five years from the ones that don't usually comes down to two things. The first is knowing the numbers. Not roughly. Actually knowing what each job costs to deliver, what the overheads are monthly, what the cash position is, what margin you need to stay healthy. The second is building even a basic structure. Roles, responsibilities, systems for how things get done. Not corporate nonsense. Just clear enough that things don't fall apart when the owner steps back.",
      "There's a common pattern I see all the time. Business does well in years one and two because the owner's energy carries it. Year three, it starts to crack because that energy isn't enough on its own. Year four and five, the owner either fixes the foundations or it falls over. The ones who fix it do so by working on the business, not just in it. They get clear on where the money's actually going, they stop taking on every job that comes in, and they build something that can run without them in every detail.",
      "If you're reading this in the first five years of your business, the most valuable thing you can do right now is sit down and work out your actual margin on the last three jobs. Not what you quoted. What you walked away with. That number will tell you a lot about where to focus.",
    ],
  },
  {
    slug: "win-profitable-work-without-cheapest-quote",
    title: "How to Win More Profitable Work Without Being the Cheapest",
    excerpt: "Competing on price is a race to the bottom. The construction businesses that grow are the ones that learn how to compete on something else entirely.",
    category: "Profit",
    readTime: "5 min read",
    date: "4 March 2026",
    content: [
      "If you're regularly losing jobs to cheaper quotes, one of two things is happening. Either you're targeting the wrong type of client, or you're not communicating your value well enough. Most of the time it's both. The instinct is to drop your price to win the work. That's the wrong move. Every time you discount to win a job, you're setting a precedent with that client, cutting into the margin you need to deliver properly, and attracting more clients who'll do the same thing again.",
      "The clients who always go with the cheapest quote are not the clients you want. They're the ones who'll call you every day on site, query every invoice, and want extras done for nothing. They're the ones who leave bad reviews when things don't go exactly to plan even though they chose the budget option. There's a type of client who wants value, not just a low price. They want someone reliable, someone who communicates, someone who does what they say they'll do. That client will pay more for certainty.",
      "Your pricing needs to reflect the actual cost of delivering a job well, plus the margin that makes it worth your while. If you haven't worked out your overhead figure, you can't price correctly. Overheads aren't just materials and labour. They're the cost of your van, insurance, tools, your own time, admin, anything that the business spends that isn't directly tied to one specific job. Until you know what that number is weekly, you're guessing.",
      "Beyond the numbers, the way you present yourself before you even get to the quote matters. Your response time, how you communicate during the quoting process, the quality of the quote itself. A detailed, professional quote that breaks down what the client is getting gives them something to compare against the guy who sent a figure on a text message. Most clients who feel uncertain about a contractor will default to the lower price because the other option didn't give them confidence. You need to give them confidence.",
      "Testimonials and photos of completed work are underused by most construction businesses. People want to see evidence. Not claims. Evidence. A portfolio of strong work with a few words from happy clients gives a new prospect a reason to trust you before they've even spoken to you. If you don't have that yet, start building it now. Ask your last three satisfied clients for a sentence or two about working with you. Most people are happy to do it if you ask directly.",
      "There's also the question of what kind of work you're going after. Not all construction work is priced the same way. Domestic clients who are spending their own money on their own home care deeply about quality and reliability. Commercial clients are often working to tight programmes with their own clients above them. Both have different priorities and different willingness to pay. Knowing who you're targeting and tailoring how you present yourself to them changes the conversation.",
      "When you're on a site visit or a client meeting, the job isn't just to look at what needs doing. It's to understand what the client actually cares about. Is it the finish? The timeline? Disruption to their household? Whatever it is, if your quote shows you understood that and planned for it, you're not just a price on a page anymore. You're the person who listened.",
      "Stop competing on price. Compete on what the client actually buys when they go with someone they trust. Reliability, communication, quality, certainty. Those things are worth more to the right client than saving a few hundred pounds on a quote they're not confident in.",
      "This week, pick one job you quoted recently that you didn't win. Write down everything you know about why. Then write down what you'd do differently in how you presented yourself, not necessarily the price. That's where the answer usually is.",
    ],
  },
  {
    slug: "building-accountability-small-construction-team",
    title: "Building Accountability in a Small Construction Team",
    excerpt: "Most construction business owners know exactly who isn't pulling their weight. The harder question is why nothing's been done about it.",
    category: "Team",
    readTime: "5 min read",
    date: "25 February 2026",
    content: [
      "Accountability in a small construction team isn't about being a hard boss. It's about being clear. Most team issues I see in construction businesses come back to one thing: the owner assumed the team knew what was expected, and the team had a completely different idea of what good looked like. Neither side is necessarily wrong. They just never agreed on the standard.",
      "The first thing you need is clarity on what each person is responsible for and what completing that responsibility looks like. Not in vague terms. Specifically. If a site foreman is responsible for daily progress on a job, what does that actually mean? Does it mean the job's on programme? Does it mean the end-of-day report is sent? Does it mean materials are ordered 48 hours ahead? Until you define it in concrete terms, you can't hold anyone to it.",
      "Once you've got that clarity, you need to communicate it. Not once in a team meeting. Regularly. Most people don't respond to one conversation about expectations. They respond to consistent reinforcement. Weekly check-ins, even short ones, where you go through what's on, what's due, and whether things are on track. That rhythm keeps everyone pointed in the same direction and gives problems a chance to surface before they become expensive.",
      "The issue most owners run into is that they've never had the direct conversation with someone who's underperforming. They've hinted. They've commented on site. They've vented to someone else. But the actual conversation, the one where you sit down and say clearly that something needs to change, hasn't happened. That conversation feels uncomfortable. It is uncomfortable. But it's the only thing that gives the person a real chance to improve. Without it, they genuinely might not know there's a problem.",
      "When you do have that conversation, it needs to be factual. Not emotional. Not based on how you felt about something. Based on what happened, what was expected, and what the gap was. If a job ran two days over programme and that cost you money, that's the conversation. What was agreed, what happened, what you need to happen differently next time. Give the person a chance to respond. Sometimes there's context you didn't have. Sometimes there isn't. Either way, you've had the conversation.",
      "Documentation matters more than most small construction business owners think. Not for legal reasons, though that's worth considering. For clarity. When you've agreed on something with a team member, write it down and make sure both of you have it. Even a quick message summing up what was discussed. It removes the 'I didn't know that was expected' conversation later and gives you something concrete to refer back to.",
      "Accountability also runs the other way. If you want your team to take ownership, you have to be consistent as the owner. If you say jobs get a proper brief on Monday morning and then you turn up with no brief on Monday, you've told the team that the standard doesn't really apply. People watch what you do far more than what you say. The culture of your business comes from you whether you intend it to or not.",
      "Small teams can hold each other accountable too, but only when the environment allows it. When the standard is clear, when there's a process for how things get done, and when everyone knows that the owner is consistent with his own expectations, the team naturally starts to pick up the slack with each other. That doesn't happen by itself. It's built over time through the owner being clear and consistent.",
      "Pick one expectation in your business that isn't being met and isn't being addressed. Write down what you expect, what's actually happening, and what a direct conversation about it would sound like. Have that conversation this week.",
    ],
  },
  {
    slug: "when-to-say-no-to-construction-work",
    title: "When to Say No to Work and Why It Grows Your Business Faster",
    excerpt: "Taking every job that comes in feels like the safe option. In most cases, it's the thing that keeps your business stuck.",
    category: "Growth",
    readTime: "5 min read",
    date: "18 February 2026",
    content: [
      "There's a version of being busy that looks like success from the outside and feels like drowning from the inside. Full order book, team on multiple sites, phone ringing constantly. But the margins are thin, the jobs are draining, and there's no room to breathe. That's what happens when you take on work without a filter. Every job that comes in gets said yes to because the fear of turning it down is greater than the cost of taking it on.",
      "The cost of taking on the wrong job is higher than most construction business owners calculate. It's not just the margin on that specific job. It's the time you spend managing a difficult client instead of doing something that moves the business forward. It's the team resources tied up on a job that's barely breaking even when there's better work available. It's the stress that bleeds into everything else when a project is wrong from the start. One bad job can set your cashflow back weeks.",
      "The clients who are most difficult to deal with often signal it before you take the job. They want to negotiate every line of the quote. They're not clear on what they want. They ask for references and then don't follow up. They're shopping around and their decision is going to be made almost entirely on price. These are things you pick up on during the quoting process. The problem is that when you need the work, you ignore those signals. The job looks good on paper so you take it anyway.",
      "Part of building a stronger business is getting clear on what type of work you actually want. Not just what you can do, what you want. The projects where you do good work, the client is reasonable, the margin is healthy, and you're not firefighting every week. When you're clear on that, you have a filter. Jobs that fit the filter get pursued properly. Jobs that don't either get declined or quoted at a price that reflects the additional pain.",
      "Saying no to a job is easier when your pipeline has something else in it. The desperation to take everything comes from not having enough options. When you've built a base of clients who come back to you, who refer you, who trust you, the decision to pass on a bad fit becomes straightforward. Building that base takes time, but it starts with how you treat your current clients and how visible you are to the type of people you want to work with.",
      "There's also the question of timing. A job that would be fine in three months is a nightmare when you're already stretched. Taking on more than your team can deliver properly is a margin killer. Rework goes up. Jobs run over. Staff cut corners because there isn't time to do it right. You end up burning profit on a job because you said yes when you should have said you could start in eight weeks. Sometimes the right answer is not no, it's not yet.",
      "The business owners who grow consistently are selective. They know their numbers. They know their capacity. They know what type of work generates the best return for the effort involved. When something comes in that doesn't fit, they either pass or price it at a level that makes it worth the hassle. That's not arrogance. That's running a business.",
      "A useful exercise is to look at your last six months of work and rate each job out of ten based on margin, client experience, and ease of delivery. The pattern that comes back will show you exactly what kind of work your business performs best on. That's the work you should be going after more of, and the kind of work that scored poorly is the kind to think twice about next time.",
      "This week, write down the type of client and the type of project that consistently produces your best results. Keep that description somewhere visible. The next time something comes in that doesn't match it, that's the job you consider saying no to.",
    ],
  },
  {
    slug: "prepare-construction-business-slow-period",
    title: "How to Prepare Your Construction Business for a Slow Period",
    excerpt: "A quiet patch in construction isn't a disaster. It's a problem you didn't plan for. The businesses that come through them strongest are the ones that saw it coming.",
    category: "Profit",
    readTime: "5 min read",
    date: "11 February 2026",
    content: [
      "Every construction business has slow periods. January and February are quieter for most domestic builders. August can go soft when clients are on holiday. There are periods when the phone just doesn't ring as much. The business owners who handle these well aren't lucky. They planned ahead. The ones who struggle are the ones who assumed the busy period would last and spent accordingly.",
      "The first thing to understand is what your monthly cost base actually is. Not roughly, specifically. What goes out every month regardless of what's coming in? Wages or subcontractor costs, vehicle expenses, insurance, software, your own drawings. That figure is your floor. It's what you need to cover before you've made a penny. When you know that number properly, you can see exactly how much runway you have if things go quiet for six, eight, ten weeks.",
      "Cash in the bank before a slow period is the single biggest buffer you can have. That sounds obvious. Most construction business owners know it in theory but struggle to build it because every time there's money in the account, there's a reason to spend it. Materials for the next job, a piece of equipment, the van that needs work. Building a cash reserve means treating it like a non-negotiable. A percentage of every invoice goes into a separate account and stays there. Even if it's just 5% to start with.",
      "Before a slow period hits, look at your pipeline. What's confirmed, what's at quote stage, and what are you chasing? Most business owners have a rough idea but haven't sat down and mapped it out properly. When you do, you usually find there are quotes sitting out there that haven't been followed up, clients who said they'd be in touch but went quiet, and referrals that were mentioned but never converted. A proper pipeline review in October or November often unearths work that gets you through the quieter months.",
      "Slow periods are also the right time to do the things you keep putting off when you're busy. The systems that need building. The processes that need documenting. The pricing structure that needs reviewing. The team conversation you've been avoiding. These things don't make you money immediately, but they make the business stronger for when it picks up. Using a quiet four weeks to sort the back office means you're not trying to fix it while you're in the middle of a busy spring.",
      "Look at your overhead spend honestly during quieter times. There are always costs that crept in during a busy period that don't need to be there. Subscriptions that aren't being used, materials that could be ordered more efficiently, jobs being done by expensive people that a cheaper solution could cover. Lean operations aren't just for slow times, but a quiet patch is the clearest moment to see where the fat is.",
      "Subcontractor relationships are worth maintaining even when you don't need them right now. The tradespeople who do good work for you want to know there's a pipeline of work. A quick call when things are quiet, letting them know what's coming up and when you'll need them, keeps that relationship warm. When the busy period hits, you're not scrambling to find reliable people at short notice.",
      "Communication with your existing clients during slow periods is also underused. Not to chase work, just to stay in touch. A message checking how a job is holding up, a follow-up six months after completion, a happy Christmas with a note about availability in January. Clients who feel looked after come back. Clients who feel like a transaction go wherever's cheapest next time.",
      "This week, work out your monthly overhead figure. Write it down. Then look at your current bank balance and your confirmed forward order book. That tells you exactly how prepared you are for a quiet period and what you need to do about it before it arrives.",
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
