import type { TrainingModule } from "./types";

export const demoModules: TrainingModule[] = [
  {
    id: "mod-1",
    title: "Financial Foundations",
    description: "Know your numbers. Understand your margins, cost your jobs properly, manage cash flow, and build a business that's actually profitable - not just busy.",
    order_index: 0,
    thumbnail_url: "/images/modules/financial.jpg",
    is_published: true,
    created_at: new Date().toISOString(),
    content: [
      {
        id: "mc-1-1",
        module_id: "mod-1",
        title: "Why Most Construction Businesses Don't Know Their Real Profit",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Most construction business owners confuse turnover with profit. In this session, we break down the difference between revenue, gross profit, and net profit - and why knowing these numbers changes every decision you make.\n\nBy the end of this training you'll understand:\n- The 3 numbers you need to check every single week\n- Why high turnover with low margin is a trap\n- How to calculate your true cost per job (including the hidden costs most people miss)",
        order_index: 0,
        duration_minutes: 18,
        attachments: [
          { id: "a-1-1", name: "Profit Calculator Spreadsheet", url: "#", type: "sheet", size: "45 KB" },
          { id: "a-1-2", name: "Weekly Numbers Checklist", url: "#", type: "pdf", size: "120 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-1-2",
        module_id: "mod-1",
        title: "Job Costing: How to Price Every Job for Profit",
        content_type: "video",
        content_url: "https://player.vimeo.com/video/1121582501?h=ad5f727774",
        content_text: "The pricing session that changes everything. We go through a real job costing example step by step - materials, labour, overheads, contingency, and margin. You'll never guess a price again.\n\nCovers:\n- The job costing formula (materials + labour + overheads + contingency + margin)\n- How to calculate your true hourly rate (it's not what you think)\n- Setting minimum margin targets per job type\n- When to walk away from a job that won't be profitable",
        order_index: 1,
        duration_minutes: 24,
        attachments: [
          { id: "a-1-3", name: "Job Costing Template", url: "#", type: "sheet", size: "62 KB" },
          { id: "a-1-4", name: "Hourly Rate Calculator", url: "#", type: "sheet", size: "38 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-1-3",
        module_id: "mod-1",
        title: "Cash Flow Management for Construction",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Cash flow kills more construction businesses than lack of work. This session covers how to build a rolling cash flow forecast, structure payment stages, and stop the feast-and-famine cycle.\n\nYou'll learn:\n- How to build an 8-week rolling cash flow forecast\n- Payment staging structures for different job sizes\n- The invoice chasing system (7/14/30 day follow-up)\n- When and how to use trade credit accounts",
        order_index: 2,
        duration_minutes: 22,
        attachments: [
          { id: "a-1-5", name: "Cash Flow Forecast Template", url: "#", type: "sheet", size: "55 KB" },
          { id: "a-1-6", name: "Invoice Chasing Scripts", url: "#", type: "pdf", size: "85 KB" },
          { id: "a-1-7", name: "Payment Terms Template", url: "#", type: "doc", size: "32 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-1-4",
        module_id: "mod-1",
        title: "Setting Your Monthly Revenue & Profit Targets",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Abstract targets like 'grow the business' mean nothing. This session walks through how to set specific, achievable monthly targets based on your actual numbers - and how to reverse-engineer what you need to do each week to hit them.",
        order_index: 3,
        duration_minutes: 14,
        attachments: [
          { id: "a-1-8", name: "Target Setting Worksheet", url: "#", type: "pdf", size: "90 KB" },
        ],
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "mod-2",
    title: "Pipeline & Sales",
    description: "Build a consistent pipeline of quality work. Stop relying on word of mouth alone. Learn to quote properly, follow up systematically, and win more of the right jobs.",
    order_index: 1,
    thumbnail_url: "/images/modules/pipeline.jpg",
    is_published: true,
    created_at: new Date().toISOString(),
    content: [
      {
        id: "mc-2-1",
        module_id: "mod-2",
        title: "Where Does Your Work Actually Come From?",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Before you spend money on marketing, you need to understand where your current work comes from. This session is an audit exercise - track every enquiry source for the next 30 days and you'll see exactly where to double down.\n\nCovers:\n- The lead source audit (where are your last 20 jobs from?)\n- Why most construction businesses over-rely on one channel\n- The 3 lead sources every trade business should have active\n- Setting up simple tracking that takes 2 minutes per day",
        order_index: 0,
        duration_minutes: 16,
        attachments: [
          { id: "a-2-1", name: "Lead Source Audit Template", url: "#", type: "sheet", size: "40 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-2-2",
        module_id: "mod-2",
        title: "The Quoting System: Speed, Clarity, Follow-Up",
        content_type: "video",
        content_url: "https://player.vimeo.com/video/1121582501?h=ad5f727774",
        content_text: "The difference between a 20% win rate and a 50% win rate isn't price - it's speed, presentation, and follow-up. This is the quoting system that turns more quotes into signed jobs.\n\nYou'll build:\n- A professional quote template with clear T&Cs\n- A standard follow-up sequence (most trades never follow up once)\n- A 'lost quote' recovery process\n- Quick-quote calculators for your top 5 job types",
        order_index: 1,
        duration_minutes: 28,
        attachments: [
          { id: "a-2-2", name: "Quote Template (Word)", url: "#", type: "doc", size: "78 KB" },
          { id: "a-2-3", name: "Follow-Up Sequence Scripts", url: "#", type: "pdf", size: "65 KB" },
          { id: "a-2-4", name: "Quick Quote Calculator", url: "#", type: "sheet", size: "52 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-2-3",
        module_id: "mod-2",
        title: "Building a Referral Engine",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Referrals are the highest quality leads in construction. But most businesses leave them to chance. This session shows you how to systematically generate referrals from every happy client.\n\nIncludes:\n- The 3-touch referral system\n- When and how to ask for referrals (timing is everything)\n- Building referral partnerships with complementary trades\n- Incentive structures that actually work",
        order_index: 2,
        duration_minutes: 19,
        attachments: [
          { id: "a-2-5", name: "Referral Request Templates", url: "#", type: "pdf", size: "45 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-2-4",
        module_id: "mod-2",
        title: "Google Business Profile: Your Free Lead Machine",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Your Google Business Profile is the single most underused free marketing tool in construction. Done properly, it puts you in front of people actively searching for your services in your area.\n\nStep-by-step setup and optimisation guide included.",
        order_index: 3,
        duration_minutes: 15,
        attachments: [
          { id: "a-2-6", name: "GBP Setup Checklist", url: "#", type: "pdf", size: "110 KB" },
          { id: "a-2-7", name: "Review Request Templates", url: "#", type: "doc", size: "28 KB" },
        ],
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "mod-3",
    title: "Building Your Team",
    description: "Hire the right people, set clear expectations, and build a team that takes ownership. Stop being the only one who cares about the work.",
    order_index: 2,
    thumbnail_url: "/images/modules/team.jpg",
    is_published: true,
    created_at: new Date().toISOString(),
    content: [
      {
        id: "mc-3-1",
        module_id: "mod-3",
        title: "When to Hire (And When Not To)",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Hiring too early burns cash. Hiring too late means you're the bottleneck. This session gives you the framework to know exactly when your business is ready for the next hire - and what role to fill first.\n\nCovers:\n- The revenue threshold for hiring\n- Direct hire vs subcontractor decision framework\n- The true cost of an employee (it's not just their wage)\n- Apprentice vs experienced: pros and cons for your stage",
        order_index: 0,
        duration_minutes: 20,
        attachments: [
          { id: "a-3-1", name: "Hiring Decision Framework", url: "#", type: "pdf", size: "95 KB" },
          { id: "a-3-2", name: "True Cost of Employee Calculator", url: "#", type: "sheet", size: "42 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-3-2",
        module_id: "mod-3",
        title: "Writing Job Descriptions That Attract the Right People",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "'Looking for a hard worker' is not a job description. This session shows you how to write clear, specific job descriptions that attract the kind of people you actually want on your team - and filter out the ones you don't.",
        order_index: 1,
        duration_minutes: 12,
        attachments: [
          { id: "a-3-3", name: "Job Description Templates (5 Roles)", url: "#", type: "doc", size: "85 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-3-3",
        module_id: "mod-3",
        title: "The First 2 Weeks: Onboarding That Sets Standards",
        content_type: "video",
        content_url: "https://player.vimeo.com/video/1121582501?h=ad5f727774",
        content_text: "How someone starts is how they continue. Most construction businesses throw new hires in at the deep end with no structure. This session gives you a 2-week onboarding plan that sets expectations from day one.\n\nIncludes:\n- Day 1 checklist (paperwork, introductions, expectations)\n- Week 1 plan (specific tasks, buddy system, daily check-ins)\n- Week 2 plan (increasing responsibility, first feedback session)\n- The 30-day review template",
        order_index: 2,
        duration_minutes: 17,
        attachments: [
          { id: "a-3-4", name: "2-Week Onboarding Checklist", url: "#", type: "pdf", size: "130 KB" },
          { id: "a-3-5", name: "30-Day Review Template", url: "#", type: "doc", size: "48 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-3-4",
        module_id: "mod-3",
        title: "Building Accountability Without Micromanaging",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "The difference between checking up on people and checking in with people. This is how you build a team that takes ownership of their work without you standing over them.\n\nCovers:\n- Setting clear expectations (what 'good' looks like)\n- The weekly team briefing (15 minutes, structured)\n- Decision-making authority frameworks\n- How to give feedback that actually changes behaviour",
        order_index: 3,
        duration_minutes: 21,
        attachments: [
          { id: "a-3-6", name: "Weekly Briefing Agenda Template", url: "#", type: "pdf", size: "55 KB" },
          { id: "a-3-7", name: "Decision Authority Matrix", url: "#", type: "sheet", size: "35 KB" },
        ],
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "mod-4",
    title: "Systems & Operations",
    description: "Build operational structure so jobs run smoother, communication is clear, and nothing falls through the cracks. The systems that let you step back from the tools.",
    order_index: 3,
    thumbnail_url: "/images/modules/systems.jpg",
    is_published: true,
    created_at: new Date().toISOString(),
    content: [
      {
        id: "mc-4-1",
        module_id: "mod-4",
        title: "Project Management for Construction (Simple Version)",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "You don't need a PhD in project management. You need a simple system that tracks what's happening on every job, what's coming next, and what's at risk. This session sets that up.\n\nWe'll build:\n- A job tracker that takes 15 minutes per morning to update\n- Stage-gate milestones for different job types\n- The traffic light system for job health\n- A weekly review process that catches problems early",
        order_index: 0,
        duration_minutes: 25,
        attachments: [
          { id: "a-4-1", name: "Job Tracker Template (Trello/Monday)", url: "#", type: "pdf", size: "2.1 MB" },
          { id: "a-4-2", name: "Stage Gate Checklist", url: "#", type: "pdf", size: "95 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-4-2",
        module_id: "mod-4",
        title: "Standard Operating Procedures (SOPs) That Actually Get Used",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "An SOP nobody reads is worthless. This session shows you how to create simple, visual, one-page SOPs for your most common processes - and how to make sure your team actually follows them.",
        order_index: 1,
        duration_minutes: 15,
        attachments: [
          { id: "a-4-3", name: "SOP Template (Fillable)", url: "#", type: "doc", size: "65 KB" },
          { id: "a-4-4", name: "Example SOPs (3 Trades)", url: "#", type: "pdf", size: "340 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-4-3",
        module_id: "mod-4",
        title: "Digital Job Sheets & Site Documentation",
        content_type: "video",
        content_url: "https://player.vimeo.com/video/1121582501?h=ad5f727774",
        content_text: "Paper job sheets get lost, damaged, and ignored. This session sets up a digital system that's actually faster than paper and gives you a complete record of every job.\n\nCovers:\n- Digital job sheet setup (Google Forms or app-based)\n- Photo documentation process (before, during, after)\n- Completion sign-off workflow\n- How this protects you legally",
        order_index: 2,
        duration_minutes: 18,
        attachments: [
          { id: "a-4-5", name: "Digital Job Sheet Template", url: "#", type: "sheet", size: "48 KB" },
        ],
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "mod-5",
    title: "Time Management & Productivity",
    description: "Stop working 60-hour weeks. Learn to plan your time, delegate effectively, and focus on the work that actually moves the business forward.",
    order_index: 4,
    thumbnail_url: "/images/modules/time.jpg",
    is_published: true,
    created_at: new Date().toISOString(),
    content: [
      {
        id: "mc-5-1",
        module_id: "mod-5",
        title: "The Owner's Weekly Planning System",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Every Sunday evening, 20 minutes. That's all it takes to plan a week that actually moves the business forward instead of just firefighting. This is the weekly planning system that gives you control of your time.\n\nIncludes:\n- The 3-bucket system (business, jobs, personal)\n- How to identify your 'CEO tasks' vs your 'employee tasks'\n- Time-blocking that works for construction schedules\n- The Friday review (10 minutes, keeps you honest)",
        order_index: 0,
        duration_minutes: 16,
        attachments: [
          { id: "a-5-1", name: "Weekly Planning Template", url: "#", type: "pdf", size: "75 KB" },
          { id: "a-5-2", name: "CEO vs Employee Task Audit", url: "#", type: "sheet", size: "30 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-5-2",
        module_id: "mod-5",
        title: "Delegation: Getting Off the Tools (For Real)",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "You can't grow a business while you're on the tools 50 hours a week. But delegating feels risky when your reputation is on the line. This session gives you a practical framework for handing things over without dropping the quality.\n\nCovers:\n- The delegation ladder (5 levels from 'do it yourself' to 'fully autonomous')\n- What to delegate first (and what to keep)\n- Setting up checkpoints so quality doesn't slip\n- How to handle the first time something goes wrong",
        order_index: 1,
        duration_minutes: 22,
        attachments: [
          { id: "a-5-3", name: "Delegation Ladder Worksheet", url: "#", type: "pdf", size: "88 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-5-3",
        module_id: "mod-5",
        title: "Eliminating Time Wasters",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "Most construction business owners lose 10+ hours per week to things that could be eliminated, automated, or delegated. This session identifies the biggest time wasters and fixes them.\n\nCommon ones we'll tackle:\n- Quoting jobs that were never going to convert\n- Driving across town for a 15-minute conversation\n- Answering the same questions from your team repeatedly\n- Chasing suppliers and payments manually",
        order_index: 2,
        duration_minutes: 13,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "mod-6",
    title: "Standards & Quality Control",
    description: "Build a reputation that wins work. Quality control checklists, client communication systems, and delivery standards that set you apart from every other trade business.",
    order_index: 5,
    thumbnail_url: "/images/modules/quality.jpg",
    is_published: false,
    created_at: new Date().toISOString(),
    content: [
      {
        id: "mc-6-1",
        module_id: "mod-6",
        title: "Quality Checklists Per Trade Stage",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "If quality depends on who's doing the job, you don't have quality - you have luck. This session builds trade-specific quality checklists that anyone on your team can follow to deliver consistent results.",
        order_index: 0,
        duration_minutes: 19,
        attachments: [
          { id: "a-6-1", name: "Quality Checklist Templates (6 Trades)", url: "#", type: "pdf", size: "220 KB" },
        ],
        created_at: new Date().toISOString(),
      },
      {
        id: "mc-6-2",
        module_id: "mod-6",
        title: "Client Communication That Builds Trust",
        content_type: "video",
        content_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        content_text: "80% of client complaints in construction come from poor communication, not poor workmanship. This session sets up a client communication system that keeps them informed, happy, and likely to refer you.",
        order_index: 1,
        duration_minutes: 14,
        attachments: [
          { id: "a-6-2", name: "Client Update Schedule Template", url: "#", type: "doc", size: "35 KB" },
          { id: "a-6-3", name: "Completion Pack Template", url: "#", type: "pdf", size: "150 KB" },
        ],
        created_at: new Date().toISOString(),
      },
    ],
  },
];

export function getDemoModules(): TrainingModule[] {
  return demoModules;
}

export function getDemoModuleById(id: string): TrainingModule | undefined {
  return demoModules.find((m) => m.id === id);
}
